package tabu;

public class EngData {

    public static final int TOPLAM = 1066;
    public static final int KLASIK_BITIS = 654;
    public static final int WINTER_BAS = 654;
    public static final int WINTER_BIT = 734;
    public static final int SPRING_BAS = 734;
    public static final int SPRING_BIT = 797;
    public static final int HOLIDAY_BAS = 797;
    public static final int HOLIDAY_BIT = 869;
    public static final int MIDNIGHT_BAS = 869;
    public static final int MIDNIGHT_BIT = 923;
    public static final int CELEBRITIES_BAS = 923;
    public static final int CELEBRITIES_BIT = 991;
    public static final int GENERALKNOWLEDGE_BAS = 991;
    public static final int GENERALKNOWLEDGE_BIT = 1066;

    private static String[][] k0() {
        return new String[][] {
            {"Backpack","travel","carry","bag","shoulder","trip"},
            {"Suitcase","luggage","travel","clothes","airport","carry"},
            {"Passport","identity","country","travel","border","document"},
            {"Ticket","travel","seat","entry","paper","transport"},
            {"Airport","plane","terminal","flight","travel","security"},
            {"Flight","plane","travel","air","journey","passenger"},
            {"Hotel","room","stay","travel","bed","service"},
            {"Reservation","booking","date","hotel","confirm","plan"},
            {"Beach","sand","sea","sun","vacation","relax"},
            {"Sunset","evening","sky","orange","horizon","sun"},
            {"Island","sea","land","tropical","remote","beach"},
            {"Forest","trees","nature","green","animals","wild"},
            {"Mountain","high","climb","rock","peak","nature"},
            {"River","water","flow","long","nature","stream"},
            {"Desert","sand","hot","dry","sun","empty"},
            {"Storm","rain","wind","thunder","lightning","weather"},
            {"Lightning","flash","sky","storm","electricity","light"},
            {"Thunder","sound","storm","loud","sky","lightning"},
            {"Rainbow","colors","sky","rain","arc","light"},
            {"Cloud","sky","white","rain","float","air"},
            {"Laptop","computer","portable","screen","keyboard","battery"},
            {"Keyboard","keys","typing","input","letters","computer"},
            {"Mouse","click","pointer","move","computer","device"},
            {"Screen","display","monitor","pixels","light","image"},
            {"Battery","power","energy","charge","device","electricity"},
            {"Charger","cable","power","plug","device","energy"},
            {"Headphones","audio","music","ears","sound","listen"},
            {"Speaker","sound","loud","music","device","audio"},
            {"Camera","photo","lens","capture","image","record"},
            {"Video","motion","recording","screen","media","play"},
            {"Game","play","fun","level","score","control"},
            {"Level","progress","stage","game","difficulty","advance"},
            {"Player","user","control","game","character","person"},
            {"Enemy","opponent","fight","game","attack","rival"},
            {"Victory","win","success","game","achievement","result"},
            {"Defeat","lose","fail","game","result","end"},
            {"Score","points","game","result","number","record"},
            {"Leaderboard","ranking","score","list","top","players"},
            {"Controller","buttons","input","game","device","control"},
            {"Console","gaming","device","screen","controller","play"},
            {"Friend","person","close","trust","talk","social"},
            {"Conversation","talk","chat","speak","discuss","words"},
            {"Message","text","send","phone","communication","reply"},
            {"Call","phone","speak","voice","connect","talk"},
            {"Reply","answer","message","respond","text","communication"},
            {"Silence","quiet","no sound","calm","still","mute"},
            {"Argument","fight","disagreement","talk","conflict","words"},
            {"Apology","sorry","mistake","forgive","regret","admit"},
            {"Trust","belief","rely","confidence","relationship","safe"},
            {"Respect","value","treat","honor","person","behavior"},
            {"School","education","class","student","teacher","learn"},
            {"Teacher","educate","class","explain","lesson","student"},
            {"Student","learn","school","study","class","exam"},
            {"Exam","test","questions","score","school","result"},
            {"Homework","task","study","school","assignment","work"},
            {"Notebook","write","pages","notes","school","paper"},
            {"Pen","write","ink","paper","tool","draw"},
            {"Board","write","chalk","class","teacher","lesson"},
            {"Lesson","subject","learn","class","topic","school"},
            {"Break","rest","time","pause","school","relax"},
            {"Doctor","hospital","patient","treat","medicine","health"},
            {"Nurse","assist","patient","care","hospital","help"},
            {"Medicine","drug","treat","health","cure","pill"},
            {"Pain","hurt","body","injury","feeling","ache"},
            {"Health","body","fitness","condition","care","life"},
            {"Exercise","fitness","movement","body","workout","health"},
            {"Running","fast","legs","move","sport","speed"},
            {"Swimming","water","pool","move","sport","breathe"},
            {"Breathing","air","lungs","inhale","exhale","life"},
            {"Heart","blood","beat","body","organ","life"},
            {"Robot","machine","move","automatic","technology","task"},
            {"AI","intelligence","learning","data","system","smart"},
            {"Code","program","write","logic","software","computer"},
            {"Bug","error","code","problem","fix","issue"},
            {"Fix","repair","solve","problem","correct","improve"},
            {"Update","new","version","improve","system","install"},
            {"Download","file","internet","save","data","transfer"},
            {"Upload","send","file","internet","data","transfer"},
            {"Network","connect","system","internet","communication","link"},
            {"Art","create","draw","paint","express","design"},
            {"Painting","colors","brush","canvas","art","image"},
            {"Music","sound","rhythm","melody","listen","song"},
            {"Song","music","lyrics","sing","audio","track"},
            {"Dance","move","rhythm","body","music","motion"},
            {"Movie","film","watch","screen","actor","story"},
            {"Actor","perform","role","film","character","scene"},
            {"Director","lead","film","scene","camera","production"},
            {"Script","write","story","dialogue","film","plan"},
            {"Scene","part","film","moment","camera","action"},
            {"Wallet","money","cards","pocket","leather","carry"},
            {"Keychain","keys","ring","small","metal","holder"},
            {"Lock","secure","key","door","safety","close"},
            {"Handle","door","hold","grip","open","metal"},
            {"Stairs","steps","up","down","building","climb"},
            {"Elevator","lift","floor","button","building","up"},
            {"Button","press","control","device","switch","click"},
            {"Remote","control","TV","buttons","signal","device"},
            {"Cable","wire","connect","power","plug","line"},
            {"Plug","socket","power","electricity","insert","cable"},
            {"Fan","air","cool","spin","summer","device"},
            {"Heater","warm","winter","heat","room","device"},
            {"Lamp","light","bulb","desk","bright","room"},
            {"Curtain","window","cover","fabric","light","close"},
            {"Carpet","floor","soft","room","fabric","walk"},
            {"Sofa","sit","living room","comfort","cushion","relax"},
            {"Chair","sit","legs","wood","furniture","table"},
            {"Table","surface","eat","work","furniture","flat"},
            {"Shelf","hold","books","wall","storage","items"},
            {"Drawer","pull","store","cabinet","slide","items"},
            {"Shirt","wear","clothes","fabric","top","button"},
            {"Jacket","coat","warm","outer","wear","winter"},
            {"Shoes","feet","walk","wear","pair","sole"},
            {"Socks","feet","pair","wear","soft","cotton"},
            {"Hat","head","wear","sun","style","cap"},
            {"Glasses","vision","lenses","wear","eyes","frame"},
            {"Watch","time","wrist","clock","wear","seconds"},
            {"Ring","finger","jewelry","gold","wear","circle"},
            {"Necklace","chain","neck","jewelry","wear","pendant"},
            {"Bracelet","wrist","jewelry","band","wear","style"},
            {"Breakfast","morning","eat","meal","start","food"},
            {"Lunch","midday","meal","eat","break","food"},
            {"Dinner","evening","meal","eat","night","food"},
            {"Snack","small","eat","quick","food","bite"},
            {"Bread","bake","slice","wheat","food","loaf"},
            {"Cheese","dairy","slice","milk","food","yellow"},
            {"Egg","shell","breakfast","cook","food","white"},
            {"Rice","grain","cook","bowl","food","white"},
            {"Soup","hot","liquid","bowl","spoon","meal"},
            {"Salad","vegetables","fresh","bowl","healthy","food"},
            {"Sugar","sweet","white","taste","food","crystals"},
            {"Salt","white","taste","food","sprinkle","sodium"},
            {"Pepper","spice","black","taste","food","grind"},
            {"Oil","liquid","cook","pan","food","fry"},
            {"Butter","dairy","spread","melt","bread","fat"},
            {"Knife","cut","sharp","blade","kitchen","tool"},
            {"Fork","prongs","eat","utensil","food","metal"},
            {"Spoon","scoop","soup","utensil","food","bowl"},
            {"Plate","dish","serve","food","round","table"},
            {"Cup","drink","liquid","handle","mug","beverage"},
            {"Coffee","drink","caffeine","cup","hot","energy"},
            {"Tea","drink","leaves","hot","cup","calm"},
            {"Juice","fruit","drink","liquid","sweet","glass"},
            {"Water","drink","clear","liquid","life","thirst"},
            {"Milk","dairy","white","drink","cow","glass"},
            {"Soda","fizzy","drink","bubbles","sweet","can"},
            {"Ice","cold","frozen","water","cube","chill"},
            {"Fridge","cold","store","food","kitchen","cool"},
            {"Freezer","freeze","cold","ice","food","storage"},
            {"Oven","bake","heat","kitchen","cook","food"},
            {"Bus","transport","city","passengers","stop","route"},
            {"Train","rail","travel","station","carriage","track"},
            {"Taxi","ride","fare","city","driver","car"},
            {"Bike","pedal","ride","wheels","street","balance"},
            {"Helmet","safety","head","wear","protect","ride"},
            {"Map","directions","location","route","guide","find"},
            {"Compass","north","direction","needle","navigate","travel"},
            {"Ticket booth","buy","entry","window","pay","line"},
            {"Turnstile","gate","entry","card","pass","station"},
            {"Platform","train","wait","station","edge","board"},
            {"Library","books","quiet","read","borrow","study"},
            {"Classroom","desks","teacher","students","lesson","school"},
            {"Projector","screen","light","presentation","image","class"},
            {"Whiteboard","write","marker","erase","class","teach"},
            {"Marker","ink","write","board","draw","pen"},
            {"Chalk","dust","write","board","class","white"},
            {"Backpack strap","shoulder","carry","bag","adjust","hold"},
            {"Locker","storage","school","lock","metal","door"},
            {"Hallway","corridor","school","walk","doors","long"},
            {"Bell","ring","class","time","school","sound"},
            {"Gym","workout","fitness","weights","exercise","room"},
            {"Treadmill","run","belt","gym","speed","machine"},
            {"Dumbbell","weight","lift","arm","gym","metal"},
            {"Barbell","weight","lift","bar","gym","strength"},
            {"Mat","floor","yoga","exercise","soft","stretch"},
            {"Stretch","muscles","extend","warmup","body","move"},
            {"Coach","train","guide","team","advice","sports"},
            {"Team","group","players","together","match","sport"},
            {"Referee","rules","whistle","judge","game","decision"},
            {"Stadium","seats","crowd","field","game","arena"},
            {"Camera lens","focus","glass","zoom","photo","optics"},
            {"Tripod","stand","stable","camera","legs","support"},
            {"Microphone stand","hold","mic","stage","adjust","pole"},
            {"Mixer","audio","levels","control","sound","board"},
            {"Headset mic","voice","gaming","talk","boom","audio"},
            {"Stream overlay","graphics","live","screen","layout","broadcast"},
            {"Chat window","messages","live","text","viewers","stream"},
            {"Clip highlight","short","video","best","share","moment"},
            {"Thumbnail","image","preview","video","small","cover"},
            {"Upload queue","pending","files","send","list","process"},
            {"Planner","schedule","dates","tasks","organize","book"},
            {"Checklist","tasks","tick","complete","list","items"},
            {"Deadline","due","time","finish","date","pressure"},
            {"Reminder","alert","time","notify","task","app"},
            {"Focus mode","block","distractions","work","concentrate","setting"},
            {"Break timer","rest","interval","time","pause","work"},
            {"Productivity","output","efficiency","work","results","focus"},
            {"Workflow","steps","process","tasks","sequence","system"},
            {"Milestone","goal","stage","project","progress","mark"},
            {"Review","check","evaluate","feedback","improve","assess"},
            {"Backyard","house","grass","fence","outside","garden"},
            {"Fence","wood","border","yard","barrier","gate"},
            {"Gate","entrance","open","close","fence","metal"},
            {"Mailbox","letters","post","mail","box","street"},
            {"Envelope","paper","letter","seal","send","address"},
            {"Stamp","mail","sticker","post","letter","cost"},
            {"Package","box","delivery","shipping","item","send"},
            {"Courier","deliver","package","service","transport","fast"},
            {"Receipt","paper","proof","purchase","store","payment"},
            {"Cashier","register","money","store","pay","counter"},
            {"Mirror","reflection","glass","face","look","image"},
            {"Toothbrush","teeth","clean","bathroom","brush","hygiene"},
            {"Toothpaste","mint","teeth","squeeze","clean","tube"},
            {"Towel","dry","water","bathroom","cloth","shower"},
            {"Soap","clean","wash","foam","hands","hygiene"},
            {"Shampoo","hair","wash","bottle","clean","shower"},
            {"Comb","hair","brush","style","teeth","straighten"},
            {"Hairdryer","blow","hot","hair","dry","device"},
            {"Sink","water","wash","faucet","bathroom","basin"},
            {"Faucet","water","turn","sink","tap","flow"},
            {"Garage","car","park","house","door","storage"},
            {"Driveway","car","path","house","park","entrance"},
            {"Sidewalk","walk","street","pavement","path","city"},
            {"Crosswalk","street","lines","walk","safe","crossing"},
            {"Traffic light","red","green","yellow","stop","go"},
            {"Speed limit","sign","road","number","drive","rule"},
            {"Parking meter","coin","time","street","pay","car"},
            {"Ticket fine","penalty","parking","rule","pay","violation"},
            {"License","drive","permit","car","legal","ID"},
            {"Insurance","policy","safety","car","coverage","pay"},
            {"Factory","production","machines","workers","industry","build"},
            {"Warehouse","storage","boxes","large","goods","inventory"},
            {"Forklift","lift","pallets","warehouse","machine","move"},
            {"Assembly line","production","process","factory","steps","build"},
            {"Blueprint","design","plan","building","drawing","architecture"},
            {"Contract","agreement","sign","legal","terms","deal"},
            {"Invoice","bill","payment","business","amount","due"},
            {"Salary","pay","monthly","job","income","money"},
            {"Bonus","extra","reward","pay","job","incentive"},
            {"Promotion","higher","job","role","advance","career"},
            {"Startup","new","company","business","idea","launch"},
            {"Pitch","present","idea","investors","talk","startup"},
            {"Investor","money","fund","business","capital","return"},
            {"Equity","ownership","shares","company","stake","value"},
            {"Revenue","income","sales","business","money","earnings"},
            {"Profit","gain","money","revenue","business","result"},
            {"Loss","negative","money","deficit","business","result"},
            {"Budget","plan","money","limit","spend","finance"},
            {"Expense","cost","spend","money","business","item"},
            {"Savings","money","store","future","bank","reserve"},
            {"Bank","money","account","deposit","withdraw","finance"},
            {"ATM","cash","machine","card","withdraw","bank"},
            {"Credit card","pay","swipe","limit","bill","plastic"},
            {"Debit card","pay","bank","account","money","swipe"},
            {"Loan","borrow","bank","interest","repay","money"},
            {"Interest","rate","money","loan","extra","percent"},
            {"Mortgage","house","loan","bank","property","payment"},
            {"Rent","pay","monthly","apartment","live","lease"},
            {"Utility bill","electricity","water","gas","pay","home"},
            {"Subscription","monthly","service","pay","renew","plan"},
            {"Garden","plants","flowers","soil","water","grow"},
            {"Shovel","dig","soil","garden","tool","ground"},
            {"Rake","leaves","gather","yard","tool","clean"},
            {"Lawnmower","grass","cut","yard","machine","lawn"},
            {"Hose","water","spray","garden","pipe","flexible"},
            {"Sprinkler","water","lawn","rotate","spray","garden"},
            {"Seeds","plant","grow","soil","small","start"},
            {"Fertilizer","nutrients","soil","plant","grow","garden"},
            {"Weeds","unwanted","plants","remove","garden","wild"},
            {"Compost","organic","waste","soil","recycle","garden"},
            {"Bakery","bread","cakes","oven","shop","bake"},
            {"Pastry","sweet","bakery","dough","dessert","treat"},
            {"Croissant","flaky","butter","pastry","French","breakfast"},
            {"Donut","sweet","fried","ring","glaze","dessert"},
            {"Cupcake","small","cake","frosting","dessert","sweet"},
            {"Pancake","flat","breakfast","syrup","pan","batter"},
            {"Waffle","grid","breakfast","syrup","iron","crisp"},
            {"Syrup","sweet","pour","pancake","sticky","liquid"},
            {"Grill","cook","meat","fire","outdoor","barbecue"},
            {"Barbecue","grill","meat","smoke","outdoor","cook"},
            {"Picnic","outdoor","food","blanket","park","relax"},
            {"Blanket","soft","cover","fabric","warm","ground"},
            {"Cooler","cold","drinks","ice","box","keep"},
            {"Thermos","hot","drink","keep","insulated","bottle"},
            {"Napkin","wipe","table","paper","clean","meal"},
            {"Trash bag","garbage","waste","plastic","throw","bin"},
            {"Recycling bin","paper","plastic","sort","waste","green"},
            {"Compost bin","organic","waste","garden","recycle","soil"},
            {"Broom","sweep","floor","clean","handle","bristles"},
            {"Dustpan","collect","dirt","sweep","floor","tray"},
            {"Laundry","wash","clothes","machine","detergent","clean"},
            {"Detergent","soap","wash","clothes","powder","liquid"},
            {"Washer","machine","clothes","spin","clean","water"},
            {"Dryer","machine","heat","clothes","dry","tumble"},
            {"Clothesline","hang","dry","outside","rope","clips"},
            {"Iron","press","clothes","heat","wrinkles","smooth"},
            {"Ironing board","flat","clothes","iron","surface","fold"},
            {"Stain","mark","clothes","remove","dirty","spot"},
            {"Bleach","whiten","clean","strong","chemical","clothes"},
            {"Fabric softener","scent","clothes","soft","wash","liquid"},
            {"Pet","animal","home","care","companion","owner"},
            {"Dog leash","walk","control","pet","strap","collar"},
            {"Cat litter","box","sand","waste","clean","pet"},
            {"Aquarium filter","water","clean","fish","tank","device"},
            {"Pet food","eat","animal","bowl","feed","kibble"},
            {"Veterinarian","doctor","animal","health","clinic","care"},
            {"Vaccination","shot","health","protect","disease","immune"},
            {"Collar tag","name","pet","ID","attach","safety"},
            {"Pet carrier","transport","cage","travel","animal","box"},
            {"Grooming","clean","brush","pet","fur","care"},
            {"Festival","event","crowd","music","celebrate","day"},
            {"Parade","street","march","floats","crowd","show"},
            {"Fireworks","sky","explode","light","celebration","night"},
            {"Carnival","rides","games","fun","fair","colorful"},
            {"Ride queue","wait","line","turn","theme","park"},
            {"Roller coaster","track","fast","drop","thrill","ride"},
            {"Ferris wheel","circle","cabins","high","view","ride"},
            {"Game booth","win","prize","toss","ring","stall"},
            {"Prize","reward","win","game","gift","award"},
            {"DNA","genes","life","structure","double helix","biology"},
            {"Atom","matter","particle","nuclear","smallest","chemistry"},
            {"Evolution","Darwin","species","change","selection","biology"},
            {"Gravity","Newton","fall","weight","orbit","pull"},
            {"Speed of Light","fastest","constant","universe","photon","E=mc2"},
            {"Electricity","current","outlet","energy","shock","volt"},
            {"Black Hole","space","gravity","light","massive","event horizon"},
            {"Galaxy","stars","space","Milky Way","huge","spinning"},
            {"Solar System","planets","sun","orbit","eight","asteroid"},
            {"Climate Change","warming","sea level","CO2","glacier","threat"},
            {"Artificial Intelligence","computer","learning","robot","future","data"},
            {"Internet","network","connection","information","fast","world"},
            {"Social Media","share","followers","platform","phone","connect"},
            {"Cryptocurrency","digital","money","bitcoin","blockchain","encrypted"},
            {"Virtual Reality","goggles","digital","experience","3D","immersive"},
            {"3D Printing","layer","plastic","invent","print","design"},
            {"Drone","fly","camera","control","unmanned","delivery"},
            {"Self-Driving Car","driverless","AI","safety","future","car"},
            {"Space Race","USA","USSR","moon","rocket","competition"},
            {"Moon Landing","1969","Apollo","Neil Armstrong","USA","historic"},
            {"SpaceX","Elon Musk","rocket","Mars","private","space"},
            {"Big Bang","universe","beginning","explosion","time","cosmology"},
            {"Quantum Physics","atom","uncertainty","wave","particle","weird"},
            {"CERN","particle","collider","Switzerland","huge","science"},
            {"Periodic Table","element","chemistry","Mendeleev","atomic number","grid"},
            {"Antibiotic","bacteria","medicine","infection","Fleming","treatment"},
            {"Cancer","cell","uncontrolled","treatment","medicine","dangerous"},
            {"COVID","pandemic","virus","global","vaccine","mask"},
            {"Brain","think","organ","neuron","center","nerve"},
            {"Consciousness","think","awake","awareness","brain","mysterious"},
            {"Memory","remember","store","brain","long short","forget"},
            {"Renewable Energy","solar","wind","clean","sustainable","electricity"},
            {"Solar Panel","energy","sun","electricity","roof","green"},
            {"Wind Turbine","energy","wind","electricity","spinning","white"},
            {"Nuclear Energy","reactor","atom","electricity","dangerous","efficient"},
            {"Fossil Fuel","oil","coal","natural gas","pollution","running out"},
            {"Biodiversity","species","nature","different","protect","ecosystem"},
            {"Ecosystem","nature","balance","living","connected","life"},
            {"Food Chain","predator","prey","eat","nature","energy"},
            {"Gene Engineering","DNA","modify","agriculture","medicine","future"},
            {"Machine Learning","computer","data","predict","model","AI"},
            {"Big Data","large","analyze","company","info","process"},
            {"Cloud Computing","internet","storage","computer","server","service"},
            {"Augmented Reality","camera","digital","real","overlay","phone"},
            {"International Space Station","space","astronaut","ISS","orbiting","science"},
            {"Hawking Radiation","Hawking","black hole","energy","evaporate","theory"},
            {"Higgs Boson","particle","mass","god particle","CERN","discovery"},
            {"Schrodinger's Cat","cat","quantum","dead","alive","same time"},
            {"Turing Test","AI","human","intelligence","conversation","distinguish"},
            {"Moore's Law","computer","chip","double","speed","transistor"},
            {"GPS","satellite","location","navigation","car","signal"},
            {"Wi-Fi","wireless","internet","signal","router","connect"},
            {"USB","connect","device","port","data","transfer"},
            {"Touchscreen","finger","phone","swipe","tap","interface"},
            {"Bluetooth","wireless","device","connect","headset","short range"},
            {"Algorithm","step","code","process","solution","computer"},
            {"Quantum Computer","fast","quantum","calculation","future","encrypted"},
            {"CRISPR","gene edit","DNA","biology","cut","discover"},
            {"Nanotech","small","atom","technology","science","material"},
            {"Brain-Computer Interface","Neuralink","brain","chip","future","connect"},
            {"Nuclear Fusion","clean","energy","sun-like","future","unlimited"},
            {"Hydrogen Fuel","clean","fuel","energy","future","zero emission"},
            {"Deepfake","video","fake","AI","realistic","mislead"},
            {"Cyberattack","hacker","system","damage","security","digital"},
            {"Encryption","secure","code","data","protect","private"},
            {"Open Source","code","free","community","share","Linux"},
            {"Operating System","software","Windows","Mac","Linux","computer"},
            {"Microprocessor","chip","small","computing","Intel","device"},
            {"Fiber Optic","internet","light","fast","cable","signal"},
            {"5G","network","fast","mobile","connection","signal"},
            {"Satellite","orbit","signal","space","GPS","communication"},
            {"Telescope","space","observe","lens","stars","distant"},
            {"Microscope","small","observe","lens","bacteria","magnify"},
            {"Vaccine","immune","disease","inject","protect","prevent"},
            {"Stem Cell","biology","potential","medicine","differentiate","treat"},
            {"Cloning","copy","DNA","controversial","identical","science"},
            {"Biopharma","medicine","biology","drugs","lab","research"},
            {"Genome","DNA","complete","mapping","human","gene"},
            {"Protein Folding","AlphaFold","shape","biology","AI","function"},
            {"Exoplanet","outside","solar system","orbit","star","discover"},
            {"Dark Matter","universe","invisible","gravity","unknown","exists"},
            {"Dark Energy","universe","expansion","unknown","accelerate","mysterious"},
            {"Wormhole","space","shortcut","time","Einstein","theoretical"},
            {"Antimatter","opposite","matter","destroy","energy","rare"},
            {"Singularity","AI","beyond","unknown","future","Kurzweil"},
            {"Nanotube","carbon","strong","small","material","nano"},
            {"Graphene","carbon","thin","strong","conduct","material"},
            {"Superconductor","electricity","zero resistance","cold","efficient","future"},
            {"Laser","light","focused","precise","cut","measure"},
            {"MRI","hospital","magnetic","scan","brain","image"},
            {"X-Ray","medical","bone","radiation","see through","hospital"},
            {"Ultrasound","sound wave","baby","medical","image","scan"},
            {"Prosthetics","artificial","limb","robot","help","replace"},
            {"Exoskeleton","robot","suit","strength","wear","help"},
            {"Autonomous Robot","move","AI","independent","future","factory"},
            {"Internet of Things","connected","device","smart home","sensor","network"},
            {"Smart Home","devices","control","phone","voice","automatic"},
            {"Electric Car","battery","charge","no gas","future","Tesla"},
            {"Hyperloop","fast","train","vacuum","Elon Musk","future"},
            {"Maglev","train","magnetic","float","fast","Japan"},
            {"Quantum Entanglement","particles","connect","distant","instant","quantum"},
            {"Teleportation","quantum","move","instant","experimental","theoretical"},
            {"Bioinformatics","biology","computer","data","genome","science"},
            {"Synthetic Biology","create","life","lab","engineer","organism"},
            {"Terraforming","Mars","change","make habitable","future","plant"},
            {"Dyson Sphere","star","energy","megastructure","sci-fi","capture"},
            {"Time Dilation","Einstein","time","speed","relativity","different"},
            {"Zero Gravity","space","float","weightless","orbit","astronaut"},
            {"Sonic Boom","sound barrier","break","plane","explosive","loud"},
            {"Bioluminescence","glow","ocean","organisms","chemical","light"},
            {"Photosynthesis","plant","sunlight","chlorophyll","oxygen","leaf"},
            {"Metabolism","body","energy","chemical","fast slow","convert"},
            {"Nervous System","brain","nerve","signal","react","body"},
            {"Immune System","fight","bacteria","white blood cell","protect","body"},
            {"Epigenetics","gene","environment","expression","inherit","change"},
            {"Microbiome","bacteria","gut","health","trillion","body"},
            {"Telomere","aging","DNA","cap","length","cell"},
            {"Autophagy","cell","clean","recycle","Nobel","healthy"},
            {"Neuroplasticity","brain","change","learn","adapt","connections"},
            {"Placebo Effect","belief","medicine","fake","real effect","mind"},
            {"Dunning-Kruger","overconfidence","knowledge","psychology","low skill","bias"},
            {"Cognitive Bias","brain","mistake","shortcut","think","psychology"},
            {"Soccer","ball","goal","field","team","kick"},
            {"Basketball","hoop","dribble","score","court","jump"},
            {"Tennis","racket","serve","court","love","deuce"},
            {"Baseball","bat","pitcher","home run","infield","strikeout"},
            {"American Football","touchdown","helmet","quarterback","field","yards"},
            {"Rugby","scrum","try","oval","tackle","pitch"},
            {"Cricket","bat","wicket","over","fielder","pitch"},
            {"Golf","club","hole","par","fairway","putt"},
            {"Volleyball","serve","spike","net","set","dig"},
            {"Track and Field","run","jump","throw","stadium","sprint"},
            {"Gymnastics","flip","beam","vault","perfect 10","stretch"},
            {"Boxing","punch","ring","round","jab","knockout"},
            {"Martial Arts","kick","form","belt","dojo","discipline"},
            {"Wrestling","pin","mat","hold","strength","grapple"},
            {"Cycling","pedal","wheel","Tour de France","gear","bike"},
            {"Triathlon","swim","bike","run","transition","endurance"},
            {"Rowing","oar","stroke","boat","river","pull"},
            {"Sailing","wind","boat","tack","regatta","navigate"},
            {"Archery","arrow","bow","target","bullseye","aim"},
            {"Fencing","sword","touch","lunge","mask","saber"},
            {"Table Tennis","paddle","spin","fast","backhand","return"},
            {"Badminton","shuttlecock","smash","net","court","feather"},
            {"Squash","racket","wall","court","bounce","enclosed"},
            {"Ice Hockey","puck","stick","skate","face-off","rink"},
            {"Figure Skating","spin","jump","ice","grace","pairs"},
            {"Ski Jumping","jump","hill","distance","fly","skis"},
            {"Bobsled","speed","ice","team","track","four man"},
            {"Luge","sled","fast","feet first","ice","time"},
            {"Biathlon","ski","shoot","target","winter","cross-country"},
            {"Chess","king","queen","checkmate","strategy","board"},
            {"Checkers","move","jump","king","board","diagonal"},
            {"Backgammon","dice","move","bear off","point","board"},
            {"Poker","bluff","cards","bet","river","Texas hold em"},
            {"Monopoly","property","bankrupt","dice","go","hotel"},
            {"Scrabble","letter","word","tile","score","triple"},
            {"Crossword","clue","across","down","fill","square"},
            {"Sudoku","number","grid","nine","logic","solve"},
            {"Jigsaw Puzzle","piece","image","fit","edge","connect"},
            {"Video Game","controller","level","score","play","screen"},
            {"e-Sports","compete","online","team","tournament","streaming"},
            {"First-Person Shooter","gun","aim","kill","team","online"},
            {"Role Playing Game","character","level up","quest","story","magic"},
            {"Strategy Game","plan","think","move","opponent","win"},
            {"Racing Game","car","speed","lap","drift","track"},
            {"Sports Management","coach","team","buy","salary","club"},
            {"Darts","throw","bullseye","180","double","board"},
            {"Billiards","cue","ball","pocket","break","solids stripes"},
            {"Bowling","strike","spare","lane","pin","approach"},
            {"Curling","stone","sweep","target","ice","team"},
            {"Orienteering","map","compass","navigate","run","forest"},
            {"Skateboarding","trick","grind","ollie","halfpipe","board"},
            {"Surfing","wave","balance","board","wipe out","tube"},
            {"Snowboarding","trick","halfpipe","powder","carve","grab"},
            {"Skiing","pole","slope","mogul","slalom","downhill"},
            {"Mountain Biking","trail","rocky","downhill","jump","mud"},
            {"Rock Climbing","hold","rope","harness","route","boulder"},
            {"Parkour","run","jump","obstacle","urban","flow"},
            {"Skydiving","freefall","parachute","altitude","drop zone","arch"},
            {"Bungee Jumping","jump","cord","rebound","fear","height"},
            {"Base Jumping","cliff","wingsuit","parachute","danger","jump"}
        };
    }

    private static String[][] k1() {
        return new String[][] {
            {"Freediving","no tank","depth","breath hold","pressure","fins"},
            {"Canyoneering","rappel","slot","water","canyon","hike"},
            {"Hunting","rifle","deer","season","camouflage","patience"},
            {"Fishing","rod","reel","cast","catch","release"},
            {"Horseback Riding","saddle","trot","canter","bridle","stable"},
            {"Polo","horse","mallet","field","goal","team"},
            {"Bullfighting","matador","bull","cape","arena","controversial"},
            {"Rodeo","cowboy","bull","rope","eight seconds","western"},
            {"Dog Racing","greyhound","track","fast","odds","sled"},
            {"Horse Racing","jockey","track","derby","odds","thoroughbred"},
            {"Formula 1","car","pit stop","podium","circuit","lap"},
            {"Motocross","dirt","jump","bike","track","helmet"},
            {"Rally Racing","car","navigator","stage","mud","drift"},
            {"Powerboat Racing","water","speed","trophy","engine","circuit"},
            {"Sumo","large","ring","push","Japan","match"},
            {"Capoeira","dance","martial","Brazil","kick","rhythm"},
            {"Kickboxing","punch","kick","ring","rounds","combination"},
            {"Muay Thai","elbow","knee","Thailand","hard","eight limbs"},
            {"Judo","throw","mat","belt","grapple","Japan"},
            {"Taekwondo","kick","jump","Korea","board break","belt"},
            {"Karate","punch","kata","dojo","belt","Japan"},
            {"Olympic Games","nation","medal","four years","athlete","flag"},
            {"Paralympic Games","disabled","athlete","medal","ability","inspire"},
            {"World Record","fastest","highest","most","achievement","Guinness"},
            {"Sports Psychology","mental","focus","pressure","athlete","performance"},
            {"Doping","banned","enhance","test","cheat","performance"},
            {"Sports Injury","ACL","sprain","recover","physio","season"},
            {"Penalty Shootout","tiebreak","stress","goalpost","nerve","final"},
            {"Hat Trick","three","goals","same player","match","rare"},
            {"Slam Dunk","basketball","jump","score","powerful","above rim"},
            {"Grand Slam","tennis","four majors","Wimbledon","title","year"},
            {"Triple Crown","horse","three","race","rare","achievement"},
            {"World Cup Trophy","gold","football","lift","win","four years"},
            {"Olympic Torch","flame","carry","ceremony","relay","light"},
            {"Scoreboard","points","display","update","watch","digital"},
            {"Locker Room","change","team","pre game","motivate","shower"},
            {"Sports Commentary","voice","describe","match","radio","TV"},
            {"Sports Betting","odds","predict","money","online","risky"},
            {"Fantasy Sports","virtual","team","player","weekly","compete"},
            {"Sports Card","collectible","trade","value","player","rare"},
            {"Mascot","costume","team","cheer","represent","animal"},
            {"Training Camp","preseason","work","intense","sweat","prepare"},
            {"Halftime Show","entertainment","music","stadium","famous","break"},
            {"Overtime","extra time","tied","sudden death","decide","tense"},
            {"Underdog","unexpected","weak","win","upset","surprise"},
            {"Dynasty","win","multiple","championship","same team","period"},
            {"Rivalry","opponent","competition","bitter","match","hatred"},
            {"Movie Sequel","part 2","follow-up","same characters","franchise","cinema"},
            {"Actress","female","perform","role","movie","star"},
            {"Screenplay","script","film","story","writer","Hollywood"},
            {"Box Office","money","film","earn","opening","record"},
            {"Film Premiere","first","red carpet","famous","event","cinema"},
            {"Oscar","award","Hollywood","Academy","statuette","ceremony"},
            {"BAFTA","British","award","film","ceremony","win"},
            {"Cannes Film Festival","French","award","Palme d Or","prestige","cinema"},
            {"Sundance","indie","film","USA","festival","discovery"},
            {"Documentary","real","story","people","film","facts"},
            {"Animation","cartoon","draw","Pixar","Disney","character"},
            {"Horror Movie","fear","scare","scream","dark","monster"},
            {"Romantic Comedy","love","funny","couple","happy ending","light"},
            {"Action Movie","explosion","fight","hero","fast","gun"},
            {"Science Fiction","future","space","robot","alien","technology"},
            {"Fantasy Movie","magic","dragon","wizard","kingdom","mythical"},
            {"Thriller","suspense","tense","mystery","plot twist","edge of seat"},
            {"Film Noir","dark","crime","shadow","detective","1940s"},
            {"Western","cowboy","gun","horse","desert","standoff"},
            {"Musical","song","dance","Broadway","stage","film"},
            {"Biopic","real person","life story","actor","historical","film"},
            {"Remake","original","new version","same story","different","film"},
            {"Blockbuster","huge","budget","spectacle","summer","franchise"},
            {"Indie Film","small","budget","independent","festival","unique"},
            {"Cult Classic","niche","following","quirky","underrated","beloved"},
            {"Cliffhanger","unresolved","suspense","wait","episode","next part"},
            {"Plot Twist","unexpected","surprise","reveal","rewatch","wow"},
            {"Character Development","grow","change","arc","journey","believable"},
            {"Special Effects","CGI","green screen","explosion","digital","visual"},
            {"Soundtrack","music","film","emotion","composer","score"},
            {"Villain","bad","evil","oppose","antagonist","scary"},
            {"Superhero","power","save","costume","DC","Marvel"},
            {"Sidekick","helper","loyal","secondary","support","comedy"},
            {"Narrator","voice","tell","story","first person","explain"},
            {"Flashback","past","memory","explain","earlier","scene"},
            {"Foreshadowing","hint","future","clue","early","predict"},
            {"Comic Book Adaptation","superhero","Marvel","DC","film","franchise"},
            {"Streaming Service","Netflix","online","watch","subscription","binge"},
            {"Binge Watching","marathon","series","hours","couch","one sitting"},
            {"TV Series","episode","season","cliffhanger","weekly","drama"},
            {"Reality TV","real people","challenge","vote","drama","unscripted"},
            {"Talk Show","host","guest","interview","discuss","daytime"},
            {"Late Night Show","comedian","celebrity","monologue","chat","night"},
            {"Stand-Up Comedy","stage","solo","laugh","set","comedian"},
            {"Podcast","audio","discuss","subscribe","episode","listen"},
            {"YouTube Channel","video","creator","subscribe","upload","view"},
            {"Influencer","social media","followers","sponsor","content","popular"},
            {"Viral Video","share","millions","spread","funny","internet"},
            {"Meme","funny","share","internet","image","text"},
            {"GIF","loop","animate","short","react","image"},
            {"Emoji","symbol","express","text","small","colorful"},
            {"Hashtag","trend","social","word","categorize","Twitter"},
            {"Caption","text","photo","describe","post","social"},
            {"Filter","camera","beautify","edit","Instagram","AR"},
            {"Followers","account","social media","count","popular","reach"},
            {"Like","heart","approval","social","count","tap"},
            {"Comment","reply","feedback","discuss","post","social"},
            {"Share","spread","forward","repost","social","viral"},
            {"Story","24 hours","disappear","Instagram","casual","quick"},
            {"Reel","short video","Instagram","TikTok","music","scroll"},
            {"TikTok","short video","dance","trend","young","popular"},
            {"Pop Music","catchy","radio","charts","popular","sing"},
            {"Rock Music","guitar","drums","loud","electric","band"},
            {"Hip Hop","rap","beat","rhythm","urban","culture"},
            {"Jazz","improvise","saxophone","smooth","club","New Orleans"},
            {"Classical Music","orchestra","symphony","refined","old","serious"},
            {"Country Music","guitar","southern","story","Nashville","cowboy"},
            {"Electronic Music","DJ","synthesizer","beat","club","digital"},
            {"K-Pop","Korean","group","choreography","fans","idol"},
            {"J-Pop","Japanese","idol","group","cute","music"},
            {"Music Video","visual","song","story","director","MTV"},
            {"Concert","live","stage","crowd","loud","tickets"},
            {"Music Festival","outdoor","stages","day","crowd","artists"},
            {"Record Label","sign","artist","music","business","contract"},
            {"Songwriter","lyrics","melody","create","compose","write"},
            {"Album","collection","songs","release","studio","vinyl"},
            {"Single","one song","release","radio","popular","hit"},
            {"Collaboration","two artists","together","feature","join","music"},
            {"Grammy","music award","ceremony","US","win","categories"},
            {"Music Theory","notes","scale","chord","rhythm","study"},
            {"Rap Battle","freestyle","competition","diss","mic","win"},
            {"Broadway","musical","New York","stage","theatrical","live"},
            {"Opera","sing","classical","drama","Italian","costumes"},
            {"Ballet","dance","classical","pointe","elegant","story"},
            {"Street Art","graffiti","urban","spray","wall","illegal"},
            {"Photography","capture","moment","lens","camera","frame"},
            {"Portrait","face","person","artist","detail","paint"},
            {"Landscape","nature","scene","paint","scenery","outdoor"},
            {"Abstract Art","non-representational","color","emotion","interpret","modern"},
            {"Sculpture","three dimensional","clay","stone","create","artist"},
            {"Architecture","design","building","structure","beautiful","engineer"},
            {"Museum","art","history","exhibit","visit","collection"},
            {"Gallery","art","show","exhibit","space","private"},
            {"Auction","bid","sell","art","price","highest"},
            {"Fashion Week","design","Paris","Milan","runway","model"},
            {"Luxury Brand","expensive","logo","status","designer","wear"},
            {"Streetwear","casual","urban","sneakers","brand","culture"},
            {"Fast Fashion","cheap","trendy","quick","environment","wear"},
            {"Sustainable Fashion","eco","ethical","material","slow","responsible"},
            {"Tattoo","permanent","ink","skin","design","needle"},
            {"Piercing","hole","jewelry","ear","nose","body"},
            {"Makeup","face","beauty","cosmetic","cover","enhance"},
            {"Skincare","routine","cream","face","protect","glow"},
            {"Hairstyle","cut","color","blow dry","curl","style"},
            {"Celebrity Gossip","scandal","relationship","break up","magazine","rumor"},
            {"Red Carpet","event","dress","glamour","celebrity","photo"},
            {"Paparazzi","photo","celebrity","chase","camera","private"},
            {"Snowfall","winter","cold","white","sky","flakes"},
            {"Blizzard","storm","snow","wind","strong","winter"},
            {"Icicle","ice","hanging","cold","roof","sharp"},
            {"Snowman","build","carrot","winter","snow","cold"},
            {"Sled","slide","snow","downhill","winter","ride"},
            {"Scarf","neck","warm","winter","clothing","cold"},
            {"Gloves","hands","warm","winter","fingers","wear"},
            {"Frost","ice","surface","cold","morning","thin"},
            {"Fireplace","fire","warm","wood","home","winter"},
            {"Hot chocolate","drink","warm","sweet","winter","mug"},
            {"Snowball","throw","fight","snow","winter","round"},
            {"Winter boots","shoes","warm","snow","feet","waterproof"},
            {"Coat","jacket","warm","winter","wear","clothing"},
            {"Beanie","hat","head","warm","winter","knit"},
            {"Thermal wear","heat","body","warm","clothing","winter"},
            {"Ice skating","rink","glide","winter","sport","blades"},
            {"Skiing","snow","slope","downhill","sport","poles"},
            {"Snowboard","board","snow","ride","winter","sport"},
            {"Avalanche","snow","fall","mountain","danger","slide"},
            {"Frozen lake","ice","water","winter","surface","cold"},
            {"Snowstorm","heavy","snow","wind","winter","storm"},
            {"Icy road","slippery","drive","danger","winter","surface"},
            {"Snowplow","clear","road","snow","vehicle","winter"},
            {"Heater","warm","room","winter","device","heat"},
            {"Radiator","heat","metal","room","warm","system"},
            {"Warm blanket","soft","cover","sleep","winter","warm"},
            {"Candlelight","flame","dim","warm","cozy","night"},
            {"Cozy cabin","wood","warm","forest","winter","stay"},
            {"Christmas tree","decorate","lights","holiday","green","pine"},
            {"Holiday lights","bright","decoration","winter","colorful","night"},
            {"Snow angel","shape","snow","body","lie","winter"},
            {"Ice fishing","hole","lake","cold","rod","winter"},
            {"Hot soup","warm","bowl","food","winter","steam"},
            {"Frozen window","ice","glass","pattern","cold","morning"},
            {"Winter sunrise","light","cold","early","sky","pink"},
            {"Long nights","dark","winter","early","sunset","time"},
            {"Snow-covered trees","white","branches","forest","winter","quiet"},
            {"Wind chill","cold","feel","temperature","winter","skin"},
            {"Ice rink","skating","frozen","surface","winter","sport"},
            {"Snow shovel","dig","clear","snow","tool","winter"},
            {"Snow boots","footwear","warm","waterproof","winter","feet"},
            {"Ice crystals","frozen","tiny","pattern","cold","formation"},
            {"Frozen breath","visible","air","cold","mouth","vapor"},
            {"Snowdrift","pile","wind","snow","shape","winter"},
            {"Ice storm","freezing","rain","dangerous","roads","winter"},
            {"Ski lift","chair","mountain","up","resort","ride"},
            {"Mountain lodge","stay","wood","fireplace","winter","rest"},
            {"Wool sweater","warm","clothing","knit","winter","soft"},
            {"Thick socks","warm","feet","winter","clothing","wool"},
            {"Thermos drink","hot","keep","liquid","winter","bottle"},
            {"Cold snap","sudden","drop","temperature","winter","weather"},
            {"Hail","ice","fall","storm","small","hard"},
            {"Black ice","invisible","slippery","road","danger","winter"},
            {"Snow chains","tires","grip","car","winter","drive"},
            {"Winter tires","car","traction","snow","safety","road"},
            {"Frozen pipe","water","burst","cold","house","winter"},
            {"Ice scraper","car","windshield","frost","clear","tool"},
            {"Defrost","melt","ice","heat","car","window"},
            {"Snowfall forecast","weather","predict","winter","report","sky"},
            {"Snow day","school","canceled","winter","fun","stay"},
            {"Winter break","holiday","school","rest","season","time"},
            {"Caroling","sing","songs","holiday","group","winter"},
            {"Gift exchange","present","trade","holiday","give","receive"},
            {"Winter festival","event","lights","cold","celebration","season"},
            {"Ice sculpture","art","frozen","carving","winter","display"},
            {"Frozen waterfall","ice","nature","cliff","winter","beauty"},
            {"Aurora","lights","sky","north","colorful","night"},
            {"Polar night","dark","long","winter","no sun","region"},
            {"Snowmobile","vehicle","ride","snow","engine","winter"},
            {"Parka","heavy","coat","warm","winter","jacket"},
            {"Ear muffs","ears","warm","winter","cover","soft"},
            {"Hand warmers","heat","small","pocket","winter","warm"},
            {"Snow goggles","eyes","protect","glare","snow","sport"},
            {"Ski poles","support","balance","skiing","snow","hands"},
            {"Lift ticket","access","ski","resort","pass","mountain"},
            {"Slope map","trails","ski","guide","mountain","paths"},
            {"Snow park","tricks","jumps","snowboard","ski","area"},
            {"Ice hotel","frozen","rooms","cold","unique","stay"},
            {"Winter sunset","sky","orange","cold","horizon","light"},
            {"Cold morning","frost","early","winter","quiet","chill"},
            {"Blossom","flower","spring","tree","bloom","petals"},
            {"Butterfly","wings","insect","colorful","fly","garden"},
            {"Rain shower","water","spring","clouds","short","wet"},
            {"Garden","plants","flowers","soil","grow","green"},
            {"Tulip","flower","spring","colorful","bulb","plant"},
            {"Pollen","allergy","yellow","plants","spring","air"},
            {"Fresh grass","green","smell","cut","spring","lawn"},
            {"Picnic","food","outdoor","blanket","park","relax"},
            {"Rainbow","colors","sky","rain","arc","light"},
            {"Spring breeze","wind","soft","fresh","air","warm"},
            {"Daffodil","yellow","flower","spring","bulb","bloom"},
            {"Cherry blossom","pink","tree","petals","spring","Japan"},
            {"Nest building","birds","twigs","spring","home","eggs"},
            {"Birdsong","chirp","morning","spring","sound","nature"},
            {"April rain","water","clouds","spring","wet","sky"},
            {"Seed planting","soil","grow","spring","garden","plant"},
            {"Flower bed","garden","colorful","soil","plants","design"},
            {"Sunshine","light","warm","sky","bright","spring"},
            {"Outdoor walk","nature","path","fresh","air","spring"},
            {"Green leaves","trees","fresh","spring","growth","nature"},
            {"Blooming trees","flowers","branches","spring","pink","white"},
            {"Spring cleaning","house","tidy","fresh","organize","clean"},
            {"Light jacket","clothing","spring","mild","wear","thin"},
            {"Morning dew","water","grass","fresh","morning","drops"},
            {"Flower market","buy","plants","colorful","street","spring"},
            {"Garden tools","shovel","rake","soil","plant","work"},
            {"Lawn mowing","cut","grass","yard","machine","spring"},
            {"Watering can","pour","plants","water","garden","tool"},
            {"Sprinkler","spray","water","lawn","garden","rotate"},
            {"Fresh air","clean","breathe","outside","spring","cool"},
            {"Cloudy sky","gray","cover","spring","weather","light"},
            {"Sun shower","rain","sun","mixed","spring","rare"},
            {"Warm afternoon","sun","mild","day","spring","relax"},
            {"Park bench","sit","wood","rest","park","outside"},
            {"Flower petals","soft","fall","colorful","blossom","ground"},
            {"Tree buds","small","new","growth","spring","leaves"},
            {"Nature walk","trail","forest","relax","spring","explore"},
            {"Fresh soil","dark","wet","garden","plant","smell"},
            {"River flow","water","move","spring","fast","nature"},
            {"Bird nest","eggs","tree","small","home","spring"},
            {"Egg hatch","break","shell","baby","bird","spring"},
            {"Farm planting","seeds","grow","crops","soil","spring"},
            {"Greenhouse","glass","plants","warm","grow","controlled"},
            {"Spring festival","event","flowers","season","celebrate","outdoor"},
            {"Kite flying","wind","sky","string","fly","spring"},
            {"Allergy season","pollen","sneeze","spring","air","reaction"},
            {"Rain boots","shoes","water","spring","wet","walk"},
            {"Umbrella","rain","cover","hold","spring","water"},
            {"Mud puddle","water","dirt","splash","spring","ground"},
            {"Sun hat","head","protect","sun","spring","wear"},
            {"Light sweater","clothing","mild","warm","spring","thin"},
            {"Outdoor caf\u00e9","coffee","sit","street","relax","spring"},
            {"Fresh fruits","sweet","juicy","market","spring","eat"},
            {"Strawberries","red","fruit","sweet","spring","fresh"},
            {"Spring vegetables","green","healthy","market","fresh","food"},
            {"Farmers market","local","food","fresh","spring","buy"},
            {"Flower bouquet","gift","flowers","wrap","colorful","give"},
            {"Bloom season","peak","flowers","spring","time","nature"},
            {"Spring sunrise","early","light","fresh","calm","sky"},
            {"Warm rain","gentle","water","spring","soft","fall"},
            {"Clean windows","wash","glass","spring","house","shine"},
            {"Open windows","air","fresh","breeze","home","spring"},
            {"Butterfly garden","plants","attract","insects","colorful","spring"},
            {"Vacation","relax","travel","break","holiday","trip"},
            {"Hotel","room","stay","service","bed","booking"},
            {"Beach","sand","sea","sun","relax","summer"},
            {"Sunbed","lie","relax","beach","sun","chair"},
            {"Swim","water","pool","sea","move","cool"},
            {"Sunscreen","protect","skin","sun","lotion","SPF"},
            {"Flip flops","sandals","beach","feet","summer","wear"},
            {"Suitcase","luggage","travel","pack","clothes","bag"},
            {"Passport","ID","travel","border","country","document"},
            {"Plane","fly","travel","air","airport","journey"},
            {"Island","sea","land","tropical","beach","remote"},
            {"Resort","luxury","hotel","relax","pool","vacation"},
            {"Buffet","food","self","eat","variety","hotel"},
            {"Cocktail","drink","glass","summer","alcohol","mix"},
            {"Boat trip","sea","ride","captain","water","travel"},
            {"Tour guide","explain","travel","place","group","lead"},
            {"Souvenir","memory","item","buy","gift","travel"},
            {"City tour","explore","streets","guide","visit","travel"},
            {"Photo shoot","camera","memory","picture","capture","travel"},
            {"Camping","tent","nature","fire","outdoor","sleep"},
            {"Hiking","walk","trail","mountain","nature","explore"},
            {"Swimming pool","water","hotel","relax","swim","blue"},
            {"Sunburn","skin","red","sun","pain","hot"},
            {"Relaxation","calm","rest","vacation","peace","free"},
            {"Travel insurance","safety","plan","risk","protection","trip"},
            {"Boarding pass","ticket","flight","seat","airport","gate"},
            {"Check-in","hotel","arrival","register","desk","stay"},
            {"Check-out","leave","hotel","payment","exit","room"},
            {"Airport security","check","bag","control","flight","scan"},
            {"Duty free","shop","airport","tax","products","store"},
            {"Luggage claim","bags","belt","airport","collect","wait"},
            {"Travel pillow","neck","comfort","plane","sleep","soft"},
            {"Window seat","plane","view","sky","seat","window"},
            {"Aisle seat","plane","walk","aisle","access","seat"},
            {"Flight delay","late","wait","airport","schedule","problem"},
            {"Travel itinerary","plan","schedule","trip","route","details"},
            {"Map reading","location","direction","guide","travel","route"},
            {"Navigation app","phone","map","GPS","route","travel"},
            {"Road trip","car","drive","journey","highway","trip"},
            {"Gas station","fuel","car","stop","travel","refill"},
            {"Car rental","vehicle","hire","travel","drive","service"},
            {"Hotel lobby","entrance","desk","wait","seating","guests"},
            {"Room service","food","hotel","order","deliver","room"},
            {"Mini bar","drinks","snacks","hotel","fridge","room"},
            {"Balcony view","outside","room","scenery","hotel","relax"},
            {"Sea view","ocean","hotel","window","water","blue"},
            {"Pool bar","drinks","water","hotel","relax","summer"},
            {"Spa treatment","relax","massage","wellness","hotel","calm"},
            {"Massage","body","relax","pressure","spa","therapy"},
            {"Sauna","heat","sweat","relax","room","spa"},
            {"Steam room","hot","vapor","relax","spa","air"},
            {"Beach umbrella","shade","sun","sand","protect","beach"},
            {"Beach towel","dry","water","sand","large","cloth"},
            {"Snorkeling","mask","water","sea","fish","explore"},
            {"Diving","deep","sea","oxygen","explore","underwater"},
            {"Surfing","waves","board","ocean","ride","sport"},
            {"Jet ski","water","speed","ride","sea","motor"},
            {"Parasailing","air","rope","sea","fly","parachute"},
            {"Boat cruise","ship","sea","relax","travel","journey"},
            {"Yacht party","luxury","boat","music","sea","party"},
            {"Island hopping","travel","islands","boat","explore","trip"},
            {"Local cuisine","food","culture","taste","restaurant","dishes"},
            {"Street food","quick","local","eat","market","cheap"},
            {"Restaurant booking","table","dinner","reserve","eat","place"},
            {"Fine dining","luxury","food","restaurant","elegant","meal"},
            {"Cafe break","coffee","relax","sit","drink","short"},
            {"Travel blog","write","share","trip","story","online"},
            {"Travel vlog","video","record","journey","share","online"},
            {"Sunrise view","early","sky","light","morning","horizon"},
            {"Sunset view","evening","sky","orange","relax","horizon"},
            {"Night market","shopping","food","lights","street","evening"},
            {"Festival trip","event","travel","culture","celebration","local"},
            {"Date night","dinner","couple","plan","romantic","evening"},
            {"Candlelight dinner","candles","table","romantic","food","dim"},
            {"Holding hands","touch","walk","couple","fingers","together"},
            {"Romantic movie","film","couple","watch","love","scene"},
            {"Sharing blanket","warm","couch","couple","cozy","together"},
            {"Midnight kiss","love","lips","romantic","moment","couple"},
            {"Slow dancing","music","move","couple","rhythm","close"},
            {"Eye contact","look","stare","connection","silent","emotion"},
            {"Love confession","admit","feelings","truth","romantic","speak"},
            {"Flirty message","text","tease","couple","phone","chat"},
            {"Goodnight message","text","sweet","sleep","couple","care"},
            {"Surprise visit","unexpected","door","couple","night","visit"},
            {"Watching stars","sky","night","couple","romantic","calm"},
            {"Shared playlist","music","couple","songs","listen","taste"},
            {"Inside jokes","laugh","couple","memory","funny","shared"},
            {"Cute nickname","name","couple","sweet","call","personal"},
            {"Comfort hug","embrace","warm","couple","support","close"},
            {"Shoulder rest","lean","calm","couple","relax","comfort"},
            {"Hair playing","touch","fingers","gentle","couple","relax"},
            {"Back hug","behind","embrace","couple","surprise","warm"},
            {"Forehead kiss","gentle","love","couple","soft","moment"},
            {"Couch cuddling","sofa","close","couple","warm","relax"},
            {"Laughing together","joy","couple","funny","moment","smile"},
            {"Secret smile","look","couple","silent","connection","hint"},
            {"Silent understanding","no words","couple","deep","connection","know"},
            {"Sharing stories","past","talk","couple","memory","night"},
            {"Dreaming together","imagine","couple","future","goals","talk"},
            {"Planning trip","vacation","couple","ideas","plan","together"},
            {"Comfort silence","quiet","couple","peace","presence","calm"},
            {"Holding gaze","eyes","couple","intense","silent","look"},
            {"Heartbeat moment","close","feel","chest","couple","calm"},
            {"Midnight coffee","awake","drink","couple","talk","energy"},
            {"Late dessert","sweet","share","couple","treat","night"},
            {"Kitchen together","cook","couple","food","late","fun"},
            {"Cooking together","prepare","food","couple","kitchen","share"},
            {"Balcony talk","outside","night","couple","quiet","city"},
            {"Sharing hoodie","clothes","warm","couple","wear","cute"},
            {"Taking selfies","photo","couple","phone","smile","memory"},
            {"Goodnight kiss","love","sleep","couple","gentle","night"},
            {"Sleepy smile","tired","couple","cute","face","calm"},
            {"Midnight laughter","joke","couple","funny","night","loud"},
            {"Playful argument","tease","couple","small","funny","talk"},
            {"Making up","sorry","hug","couple","fix","love"},
            {"Emotional support","help","feelings","couple","comfort","care"},
            {"Checking in","ask","okay","couple","care","message"},
            {"Late confession","truth","couple","feelings","honest","night"},
            {"Random compliment","praise","couple","smile","sweet","say"},
            {"Blushing moment","shy","couple","cute","reaction","face"},
            {"Shy smile","nervous","couple","cute","small","face"},
            {"Playful push","touch","joke","couple","fun","light"},
            {"Tickle fight","laugh","couple","playful","touch","funny"},
            {"Pillow talk","bed","quiet","couple","talk","night"},
            {"Soft whisper","quiet","voice","couple","ear","close"},
            {"Breathing together","calm","slow","couple","rhythm","relax"},
            {"Taylor Swift","singer","albums","Eras Tour","country pop","songwriting"},
            {"Cristiano Ronaldo","football","Portugal","goals","striker","Al Nassr"},
            {"Lionel Messi","Argentina","football","World Cup","Barcelona","dribble"},
            {"Selena Gomez","singer","actress","Disney","Rare Beauty","pop"},
            {"Justin Bieber","singer","pop","Canada","hits","fanbase"},
            {"Beyonc\u00e9","singer","queen","albums","performance","R&B"},
            {"Drake","rapper","Canada","charts","music","hits"},
            {"Rihanna","singer","fashion","beauty","Fenty","Barbados"},
            {"Ed Sheeran","singer","guitar","acoustic","songs","UK"},
            {"Billie Eilish","singer","unique","style","dark pop","voice"},
            {"Leonardo DiCaprio","actor","Titanic","Oscar","films","Hollywood"},
            {"Brad Pitt","actor","movies","Hollywood","Fight Club","star"},
            {"Angelina Jolie","actress","humanitarian","films","Hollywood","Tomb Raider"},
            {"Scarlett Johansson","actress","Marvel","Black Widow","films","star"},
            {"Chris Hemsworth","actor","Thor","Marvel","Australia","muscles"},
            {"Tom Holland","actor","Spider Man","Marvel","young","films"},
            {"Zendaya","actress","fashion","Euphoria","Disney","style"},
            {"Jennifer Lawrence","actress","Hunger Games","Oscar","films","star"},
            {"Emma Watson","actress","Harry Potter","books","activist","UK"},
            {"Dwayne Johnson","actor","wrestler","strong","movies","Hollywood"},
            {"Keanu Reeves","actor","Matrix","John Wick","humble","films"},
            {"Johnny Depp","actor","Pirates","character","films","Hollywood"},
            {"Will Smith","actor","rapper","movies","fame","awards"},
            {"Chris Evans","actor","Captain America","Marvel","films","hero"},
            {"Margot Robbie","actress","Barbie","films","Hollywood","star"},
            {"Ryan Reynolds","actor","Deadpool","humor","films","Canada"},
            {"Hugh Jackman","actor","Wolverine","musical","films","Australia"},
            {"Gal Gadot","actress","Wonder Woman","films","model","Israel"},
            {"Henry Cavill","actor","Superman","Witcher","strong","films"},
            {"Kim Kardashian","reality","fashion","influencer","brand","social"},
            {"Kylie Jenner","beauty","billionaire","makeup","brand","influencer"},
            {"Kanye West","rapper","producer","fashion","controversial","music"},
            {"Travis Scott","rapper","concerts","music","hype","crowd"},
            {"Ariana Grande","singer","voice","high notes","pop","songs"},
            {"Shawn Mendes","singer","guitar","pop","Canada","songs"},
            {"Dua Lipa","singer","dance pop","UK","hits","style"},
            {"Harry Styles","singer","One Direction","fashion","solo","albums"},
            {"Zayn Malik","singer","One Direction","solo","voice","songs"},
            {"Nicki Minaj","rapper","female","style","lyrics","music"},
            {"Elon Musk","entrepreneur","Tesla","SpaceX","tech","billionaire"},
            {"Mark Zuckerberg","Facebook","tech","CEO","social","founder"},
            {"Jeff Bezos","Amazon","billionaire","business","founder","space"},
            {"Bill Gates","Microsoft","tech","billionaire","philanthropy","software"},
            {"Steve Jobs","Apple","innovation","iPhone","tech","founder"},
            {"Sundar Pichai","Google","CEO","tech","leadership","company"},
            {"Tim Cook","Apple","CEO","business","tech","leadership"},
            {"Sam Altman","AI","OpenAI","tech","CEO","startup"},
            {"Larry Page","Google","founder","tech","search","internet"},
            {"Sergey Brin","Google","cofounder","tech","search","innovation"},
            {"LeBron James","basketball","NBA","Lakers","points","legend"},
            {"Michael Jordan","basketball","NBA","Bulls","legend","shoes"},
            {"Kobe Bryant","basketball","NBA","Lakers","legend","mamba"},
            {"Stephen Curry","basketball","NBA","shooting","Warriors","three"},
            {"Kevin Durant","basketball","NBA","scoring","Nets","star"},
            {"Neymar Jr","football","Brazil","PSG","skills","flair"},
            {"Kylian Mbappe","football","France","speed","PSG","goals"},
            {"Erling Haaland","football","goals","striker","Norway","City"},
            {"Mohamed Salah","football","Egypt","Liverpool","winger","goals"},
            {"Virat Kohli","cricket","India","runs","captain","batsman"},
            {"Oprah Winfrey","talk show","host","media","influence","TV"},
            {"Ellen DeGeneres","host","comedy","talk show","TV","humor"},
            {"Jimmy Fallon","host","late night","comedy","show","TV"},
            {"Trevor Noah","comedian","host","news","satire","show"},
            {"MrBeast","YouTube","challenges","giveaways","viral","content"},
            {"PewDiePie","YouTube","gaming","Sweden","subscribers","content"},
            {"Logan Paul","YouTube","boxing","influencer","content","fame"},
            {"Addison Rae","TikTok","dance","influencer","social","fame"},
            {"Charli DAmelio","TikTok","dance","viral","influencer","fame"},
            {"Gravity","force","earth","pull","fall","physics"},
            {"Atom","tiny","particle","matter","science","nucleus"},
            {"Molecule","atoms","bond","chemistry","structure","compound"},
            {"Cell","biology","organism","nucleus","membrane","life"},
            {"Photosynthesis","plants","sunlight","energy","leaves","oxygen"},
            {"Evolution","species","change","Darwin","biology","adaptation"},
            {"Solar system","sun","planets","orbit","space","astronomy"},
            {"Galaxy","stars","universe","space","cluster","milky way"},
            {"Black hole","gravity","space","light","infinite","mass"}
        };
    }

    private static String[][] k2() {
        return new String[][] {
            {"Planet","orbit","space","world","sphere","system"},
            {"Earth","planet","humans","land","water","life"},
            {"Continent","land","earth","region","map","geography"},
            {"Ocean","water","deep","sea","waves","blue"},
            {"River","flow","water","long","nature","stream"},
            {"Mountain","high","peak","climb","rock","nature"},
            {"Desert","dry","sand","hot","empty","climate"},
            {"Climate","weather","temperature","long term","environment","change"},
            {"Ecosystem","nature","organisms","environment","balance","life"},
            {"Biodiversity","species","variety","life","nature","ecosystem"},
            {"Electricity","energy","current","power","wires","light"},
            {"Magnet","attraction","poles","metal","force","physics"},
            {"Voltage","electricity","energy","circuit","power","flow"},
            {"Battery","power","energy","store","device","charge"},
            {"Circuit","electricity","path","wires","flow","system"},
            {"Light","energy","bright","vision","waves","physics"},
            {"Sound","vibration","waves","hear","audio","frequency"},
            {"Heat","temperature","energy","warm","transfer","physics"},
            {"Pressure","force","area","gas","physics","measure"},
            {"Speed","distance","time","motion","fast","velocity"},
            {"History","past","events","timeline","records","knowledge"},
            {"Ancient Egypt","pyramids","Nile","pharaoh","history","civilization"},
            {"Roman Empire","Rome","empire","history","ancient","power"},
            {"Middle Ages","knights","castles","history","era","Europe"},
            {"Renaissance","art","Europe","rebirth","history","culture"},
            {"Industrial Revolution","machines","factories","history","change","production"},
            {"Cold War","tension","USA","USSR","politics","history"},
            {"Democracy","voting","government","people","system","rights"},
            {"Economy","money","trade","market","finance","system"},
            {"Inflation","prices","economy","rise","money","value"},
            {"Supply","goods","market","economy","provide","quantity"},
            {"Demand","need","market","economy","buy","desire"},
            {"Trade","exchange","goods","countries","economy","business"},
            {"Currency","money","value","coins","notes","finance"},
            {"Bank","money","account","finance","deposit","withdraw"},
            {"Investment","money","risk","profit","business","future"},
            {"Stock market","shares","trade","money","company","finance"},
            {"Language","words","speak","grammar","communication","talk"},
            {"Alphabet","letters","language","write","symbols","system"},
            {"Grammar","rules","language","structure","sentences","correct"},
            {"Translation","language","convert","meaning","words","text"},
            {"Communication","talk","message","speak","exchange","information"},
            {"Culture","traditions","society","customs","people","lifestyle"},
            {"Religion","belief","faith","god","worship","system"},
            {"Philosophy","thinking","ideas","logic","meaning","life"},
            {"Psychology","mind","behavior","brain","thoughts","science"},
            {"Sociology","society","groups","people","behavior","study"},
            {"Internet","network","online","connect","web","data"},
            {"Website","page","internet","browser","content","online"},
            {"Search engine","Google","find","results","web","search"},
            {"Social media","apps","share","content","online","people"},
            {"Email","message","send","inbox","communication","digital"},
            {"Software","program","computer","code","application","system"},
            {"Hardware","physical","computer","device","parts","machine"},
            {"Artificial intelligence","learning","data","system","smart","tech"},
            {"Algorithm","steps","logic","code","process","solution"},
            {"Data","information","numbers","analysis","storage","facts"},
            {"Innovation","new","idea","create","progress","technology"},
            {"Discovery","find","explore","science","new","knowledge"},
            {"Experiment","test","science","results","lab","trial"},
            {"Theory","idea","explanation","science","concept","model"},
            {"Measurement","value","units","scale","number","calculate"},
            {"Time","clock","seconds","hours","measure","duration"},
            {"Distance","length","space","measure","far","units"},
            {"Energy","power","work","physics","force","motion"},
            {"Mass","weight","object","physics","matter","measure"}
        };
    }

    public static String ana(int i) {
        if (i < 500) { String[][] a = k0(); return a[i-0][0]; }
        if (i < 1000) { String[][] a = k1(); return a[i-500][0]; }
        if (i < 1066) { String[][] a = k2(); return a[i-1000][0]; }
        return "";
    }

    public static String yasak(int i, int j) {
        if (i < 500) { String[][] a = k0(); return a[i-0][j+1]; }
        if (i < 1000) { String[][] a = k1(); return a[i-500][j+1]; }
        if (i < 1066) { String[][] a = k2(); return a[i-1000][j+1]; }
        return "";
    }
}
